# Generated by Django 4.2.5 on 2023-09-16 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('reason', models.CharField(max_length=255, verbose_name='Motivo')),
                ('billing_date', models.DateField(verbose_name='Data de cobrança')),
                ('paid', models.BooleanField(default=False, verbose_name='Pago')),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('reason', models.CharField(max_length=255, verbose_name='Motivo')),
                ('payment_date', models.DateField(verbose_name='Data de pagamento')),
                ('paid', models.BooleanField(default=False, verbose_name='Pago')),
            ],
        ),
    ]
